In [ ]:
#@title Twitter Auth Token

twitter_auth_token = 'input twitter auth token here'

In [ ]:
# Install Node.js dan dependency untuk tweet-harvest
!sudo apt-get update

# Install package dasar untuk menambahkan repository NodeSource
!sudo apt-get install -y ca-certificates curl gnupg

# Tambahkan repository Node.js 20
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

# Update setelah repository Node.js ditambahkan, lalu install Node.js dan dependency browser
!sudo apt-get update
!sudo apt-get install -y nodejs \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxfixes3 \
  libxrandr2 \
  libgbm1 \
  libgtk-3-0 \
  libnss3 \
  libasound2

# Cek versi Node.js
!node -v

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://cli.github.com/packages stable InRelease [3,917 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:6 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,607 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,313 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,400 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,974 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,129 kB]
Get:15 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,299 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.3 MB]
Get:18 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.9 kB]
Get:19 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,042 kB]
Fetched 39.5 MB in 7s (5,620 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.24).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:5 https://cli.github.com/packages stable InRelease
Get:6 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [14.7 kB]
Fetched 26.8 kB in 1s (23.6 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libcups2 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.3).
libnss3 set to manually installed.
Suggested packages:
  gvfs
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libgtk-3-0 libgtk-3-bin libgtk-3-common
  librsvg2-common libxcomposite1 libxtst6 nodejs session-migration
0 upgraded, 14 newly installed, 0 to remove and 14 not upgraded.
Need to get 35.9 MB of archives.
After this operation, 209 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:12 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.20.2-1nodesource1 [32.2 MB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-bin amd64 3.24.33-1ubuntu2.2 [69.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 librsvg2-common amd64 2.52.5+dfsg-3ubuntu0.2 [17.7 kB]
Fetched 35.9 MB in 1s (36.5 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 14.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 118242 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../05-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../06-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../07-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../08-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../09-libgtk-3-common_3.24.33-1ubuntu2.2_all.deb ...
Unpacking libgtk-3-common (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-0:amd64.
Preparing to unpack .../10-libgtk-3-0_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../11-libgtk-3-bin_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../12-librsvg2-common_2.52.5+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../13-nodejs_20.20.2-1nodesource1_amd64.deb ...
Unpacking nodejs (20.20.2-1nodesource1) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up nodejs (20.20.2-1nodesource1) ...
Setting up librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libgtk-3-common (3.24.33-1ubuntu2.2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.5) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

Setting up libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Setting up at-spi2-core (2.44.0-3) ...
v20.20.2

In [ ]:
# Crawl Data

filename = 'Keracunan_mbg.csv'
search_keyword = 'keracunan mbg'
limit = 3000

!npx --yes tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
⠙npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
⠙npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: keracunan mbg

 (3) (4) (5) (6) (7) (8) (9)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 80

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 100

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 120

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 140

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 160

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 180

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 200

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 220

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 240

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 260

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 280

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 300

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 320

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 340

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 360

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 380

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 400

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 420

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 440

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 458

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 476

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 494

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 513

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 528

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 542

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 556

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 571

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 585

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 594

-- Scrolling... (1)[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 595

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg.csv
Total tweets saved: 598
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5)[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@7932e5f37be482b640af52e9825e2d44"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 598 tweets, done scrolling...
⠙npm notice
npm notice New major version of npm available! 10.8.2 -> 11.16.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.16.0
npm notice To update run: npm install -g npm@11.16.0
npm notice
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

# Check the length of the DataFrame
num_rows = len(df)
print(f"The number of rows in the DataFrame is: {num_rows}")

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2062107361217810817,Wed Jun 03 09:41:21 +0000 2026,13,Media Asing Sorot Prabowo Ganti Kepala BGN Seb...,2062107361217810817,https://pbs.twimg.com/media/HJ4Tt3jaUAATqNn.jpg,NaN,in,NaN,0,3,7,https://x.com/undefined/status/206210736121781...,80559922,NaN
1,1922880360930505152,Thu May 15 06:38:09 +0000 2025,17429,@txtdrimedia Berikut ini perkiraan penyebab ke...,1922904317356298676,NaN,txtdrimedia,in,NaN,80,73,1267,https://x.com/undefined/status/192290431735629...,1868161628342194176,NaN
2,2059563130213331392,Thu May 28 04:30:27 +0000 2026,1,@TeddGus Santai aja @TeddGus .. ngapain lw res...,2059854794479771770,NaN,TeddGus,in,NaN,0,0,0,https://x.com/undefined/status/205985479447977...,1639998093080031233,NaN
3,2061055979257774506,Sun May 31 22:34:46 +0000 2026,13,@Ogaman888 Kalo orang pinter dan ga rakus ide ...,2061214835304730732,NaN,Ogaman888,in,NaN,0,0,0,https://x.com/undefined/status/206121483530473...,1678102649676103680,NaN
4,2060508822570250314,Sat May 30 02:47:53 +0000 2026,1,@mfsa118 kata pemilihnya karna beliau backgrou...,2060553755674943531,NaN,mfsa118,in,NaN,0,0,0,https://x.com/undefined/status/206055375567494...,1711883454969962496,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,2062209844569080080,Wed Jun 03 16:28:35 +0000 2026,0,Benerkan Omongan Gue soal KORUPSI MBG &amp; KE...,2062209844569080080,https://pbs.twimg.com/media/HJ5w7JhagAEm2Bb.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/206220984456908...,608715158,NaN
594,2062366904829043089,Thu Jun 04 08:05:15 +0000 2026,0,@KangManto123 Dihukum babat sawit pake parang ...,2062445565284438208,NaN,KangManto123,in,NaN,0,0,0,https://x.com/undefined/status/206244556528443...,1180616529697595393,NaN
595,2062445751783829764,Thu Jun 04 08:06:00 +0000 2026,0,Modus Korupsi MBG Terungkap Begini Cara Dadan ...,2062445751783829764,https://pbs.twimg.com/media/HJ8suYCaUAA0ZsH.png,NaN,in,NaN,0,0,0,https://x.com/undefined/status/206244575178382...,786549338818224128,NaN
596,2062445792187822242,Thu Jun 04 08:06:09 +0000 2026,0,Sebenarnya gak masalah kalau dia mengurusi MBG...,2062445792187822242,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/206244579218782...,1456857857186361356,NaN
597,2062366904829043089,Thu Jun 04 08:05:51 +0000 2026,0,@KangManto123 @Naandaa27 Telanjangin sempakan ...,2062445716883272071,NaN,KangManto123,in,NaN,0,0,0,https://x.com/undefined/status/206244571688327...,1220001613361770497,NaN

The number of rows in the DataFrame is: 598

In [3]:
import pandas as pd

# Load dataset
df = pd.read_csv("Keracunan_mbg.csv")

# Lihat nama kolom
print(df.columns)

# Filter tweet dengan minimal 50 komentar
df_filtered = df[df['reply_count'] >= 50]

# Jumlah data setelah filter
print(f"Jumlah tweet setelah filter: {len(df_filtered)}")

# Simpan hasil
df_filtered.to_csv("Keracunan_mbg_min_reply_50.csv", index=False)

# Tampilkan beberapa data
df_filtered.head()

Index(['conversation_id_str', 'created_at', 'favorite_count', 'full_text',
       'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location',
       'quote_count', 'reply_count', 'retweet_count', 'tweet_url',
       'user_id_str', 'username'],
      dtype='object')
Jumlah tweet setelah filter: 74

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
1,1922880360930505152,Thu May 15 06:38:09 +0000 2025,17429,@txtdrimedia Berikut ini perkiraan penyebab ke...,1922904317356298676,NaN,txtdrimedia,in,NaN,80,73,1267,https://x.com/undefined/status/192290431735629...,1868161628342194176,NaN
16,1920120177640751272,Wed May 07 14:14:59 +0000 2025,15559,PONAKANKU KERACUNAN MBG .. KAMPANG PEMERINTAH ...,1920120177640751272,NaN,NaN,in,NaN,102,98,2080,https://x.com/undefined/status/192012017764075...,204476230,NaN
25,2059678899399991686,Wed May 27 16:51:31 +0000 2026,29109,Jangan tutup mata kalau MBG tuh memotong angga...,2059678899399991686,NaN,NaN,in,NaN,77,100,13715,https://x.com/undefined/status/205967889939999...,1721396392873299968,NaN
35,1961120120841163127,Thu Aug 28 19:27:29 +0000 2025,26734,@txtdrimedia Udah nih ??? Maaf doang ??? Gamma...,1961148650379427927,NaN,txtdrimedia,in,NaN,44,52,5499,https://x.com/undefined/status/196114865037942...,1329611765185822721,NaN
38,2029407313958977673,Thu Mar 05 04:03:02 +0000 2026,27258,MIRIS... VALENCIA JURNALIS CNN MEMBONGKAR KERA...,2029407313958977673,https://pbs.twimg.com/media/HCnnMo_awAQqiaA.jpg,NaN,in,NaN,994,809,12497,https://x.com/undefined/status/202940731395897...,1773641343858024448,NaN